
language: ruby

rvm:
  - 2.5.1

before_script:
  - cp config/database.yml.example config/database.yml
  - bin/rake db:create

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bundle exec overcommit --sign && bundle exec overcommit --run
