# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d223490ef24539382493c662e28a173fbd7163d4a5df46d44577118c12af95eb60ceacb1dc1246540c305233e5f84b5af57fe8a2603c2957bdb1c2722de2081

test:
  secret_key_base: 658fcb2e1ff1582650328e6b5db5cd2d0c93de5f6dcd043f108f4e3e42b9e4d04b7de0425b952e01a201f99698235b9b748704992329e574b7b35d45497d37d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
